### ISSUE TITLE
Installation under windows fails because of zlib

### ISSUE THREAD

**Issue by JonasJurczok** [JonasJurczok/faketorio#48]
luarocks install faketorio ZLIB_DIR=C:\MinGW\msys\1.0\bin ZLIB_INCDIR=C:\MinGW\msys\1.0\include

**Comment by JonasJurczok** [comment]
Maybe move to https://github.com/SafeteeWoW/LibDeflate ?

**Comment by JonasJurczok** [comment]
Are we actually using this? as far as I can see I dropped the zlib dependency in the code but not in the rockspec..

**Comment by JonasJurczok** [comment]
On other operating systems installing zlib is no problem.

Idea: on windows don't require luarocks and zlib but instead execute the binary from luarocks directly. This is ultra hacky, but seems to be the only stable way of doing it.

**Comment by Tarrke** [comment]
I am at work today. I can try installing faketorio on Windows if that's
helping you. Just let me know what to test.
